In [2]:
import pandas as pd

In [3]:
c_f=pd.read_csv("unesco_sites.csv")

In [4]:
c_f.head()

,category,states_name_en,region_en,unique_number,id_no,rev_bis,name_en,short_description_en,justification_en,date_inscribed,...,date_end,danger_list,longitude,latitude,area_hectares,criteria_txt,category_short,iso_code,udnp_code,transboundary
0,Cultural,Afghanistan,Asia and the Pacific,230,208,Rev,Cultural Landscape and Archaeological Remains ...,The cultural landscape and archaeological rem...,<em>Criterion (i):</em> The Buddha statues an...,2003,...,NaN,Y 2003,67.825250,34.846940,158.9265,(i)(ii)(iii)(iv)(vi),C,af,afg,0
1,Cultural,Afghanistan,Asia and the Pacific,234,211,Rev,Minaret and Archaeological Remains of Jam,"The 65m-tall Minaret of Jam is a graceful, so...",<em>Criterion (ii):</em> The innovative archi...,2002,...,NaN,Y 2002,64.515889,34.396417,70.0000,(ii)(iii)(iv),C,af,afg,0
2,Cultural,Albania,Europe and North America,1590,569,Bis,Historic Centres of Berat and Gjirokastra,Berat and Gjirokastra are inscribed as rare e...,NaN,2005,...,NaN,NaN,20.133333,40.069444,58.9000,(iii)(iv),C,al,alb,0
3,Cultural,Albania,Europe and North America,1563,570,ter,Butrint,"Inhabited since prehistoric times, Butrint ha...",NaN,1992,...,2005.0,P 1997-2005,20.026111,39.751111,NaN,(iii),C,al,alb,0
4,Cultural,Algeria,Arab States,111,102,NaN,Al Qal'a of Beni Hammad,In a mountainous site of extraordinary beauty...,NaN,1980,...,NaN,NaN,4.786840,35.818440,150.0000,(iii),C,dz,dza,0

# Data cleaning
1. Check for duplicates and handle them
2. Check for missing values and handle them
3. Check for invalid data types and handle them
4. Drop the unwanted columns

 Check for duplicates

In [5]:
c_f.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1116    False
1117    False
1118    False
1119    False
1120    False
Length: 1121, dtype: bool

In [6]:
c_f.duplicated().any()

np.False_

In [7]:
c_f.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1116    False
1117    False
1118    False
1119    False
1120    False
Length: 1121, dtype: bool

In [8]:
c_f.duplicated().any()

np.False_

In [9]:
c_df=c_f.drop_duplicates()

In [10]:
c_df.shape

(1121, 22)

In [11]:
c_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   category              1121 non-null   str
 1   states_name_en        1121 non-null   str
 2   region_en             1121 non-null   str
 3   unique_number         1121 non-null   int64
 4   id_no                 1121 non-null   int64
 5   rev_bis               267 non-null    str
 6   name_en               1121 non-null   str
 7   short_description_en  1121 non-null   str
 8   justification_en      334 non-null    str
 9   date_inscribed        1121 non-null   int64
 10  secondary_dates       87 non-null     str
 11  danger                1121 non-null   int64
 12  date_end              39 non-null     float64
 13  danger_list           88 non-null     str
 14  longitude             1121 non-null   float64
 15  latitude              1121 non-null   float64
 16  area_hectares         1101 non-null   float64
 17  criteria_txt          1121 non-null   str
 18  category_short        1121 non-null   str
 19  iso_code              1120 non-null   str
 20  udnp_code             1120 non-null   str
 21  transboundary         1121 non-null   int64
dtypes: float64(4), int64(5), str(13)
memory usage: 192.8 KB

 Check missing values

In [12]:
c_df.isnull()

,category,states_name_en,region_en,unique_number,id_no,rev_bis,name_en,short_description_en,justification_en,date_inscribed,...,date_end,danger_list,longitude,latitude,area_hectares,criteria_txt,category_short,iso_code,udnp_code,transboundary
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,True,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,True,False,False,True,False,...,True,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,False,False,False,False,False,False,False,False,True,False,...,True,True,False,False,True,False,False,False,False,False
1117,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
1118,False,False,False,False,False,True,False,False,True,False,...,True,True,False,False,False,False,False,False,False,False
1119,False,False,False,False,False,False,False,False,True,False,...,True,True,False,False,False,False,False,False,False,False
1120,False,False,False,False,False,True,False,False,True,False,...,True,True,False,False,False,False,False,False,False,False

In [13]:
c_df.isnull().sum()

category                   0
states_name_en             0
region_en                  0
unique_number              0
id_no                      0
rev_bis                  854
name_en                    0
short_description_en       0
justification_en         787
date_inscribed             0
secondary_dates         1034
danger                     0
date_end                1082
danger_list             1033
longitude                  0
latitude                   0
area_hectares             20
criteria_txt               0
category_short             0
iso_code                   1
udnp_code                  1
transboundary              0
dtype: int64

In [14]:
c_df.shape

(1121, 22)

In [15]:
c_df.columns

Index(['category', 'states_name_en', 'region_en', 'unique_number', 'id_no',
       'rev_bis', 'name_en', 'short_description_en', 'justification_en',
       'date_inscribed', 'secondary_dates', 'danger', 'date_end',
       'danger_list', 'longitude', 'latitude', 'area_hectares', 'criteria_txt',
       'category_short', 'iso_code', 'udnp_code', 'transboundary'],
      dtype='str')

 Drop columns with too many missing values

In [16]:
c_df=c_df.drop(columns=['unique_number','id_no','rev_bis','short_description_en','secondary_dates','date_end','danger_list','criteria_txt','iso_code','udnp_code','transboundary','category_short'])

In [17]:
c_df.columns

Index(['category', 'states_name_en', 'region_en', 'name_en',
       'justification_en', 'date_inscribed', 'danger', 'longitude', 'latitude',
       'area_hectares'],
      dtype='str')

In [18]:
c_df = c_df.drop('justification_en', axis=1)

Change datatypes

In [19]:
# Fill text columns with 'Unknown'
c_df['states_name_en'] = c_df['states_name_en'].fillna('Unknown')

c_df['region_en'] = c_df['region_en'].fillna('Unknown')

c_df['category'] = c_df['category'].fillna('Unknown')

c_df['name_en'] = c_df['name_en'].fillna('Unknown')

Convert year column to numeric

In [20]:
c_df['date_inscribed'] = c_df['date_inscribed'].fillna(0)

c_df['longitude'] = c_df['longitude'].fillna(0)

c_df['latitude'] = c_df['latitude'].fillna(0)

c_df['area_hectares'] = c_df['area_hectares'].fillna(0)

In [21]:
c_df.isnull().sum()

category          0
states_name_en    0
region_en         0
name_en           0
date_inscribed    0
danger            0
longitude         0
latitude          0
area_hectares     0
dtype: int64

In [22]:
c_df.head()

,category,states_name_en,region_en,name_en,date_inscribed,danger,longitude,latitude,area_hectares
0,Cultural,Afghanistan,Asia and the Pacific,Cultural Landscape and Archaeological Remains ...,2003,1,67.825250,34.846940,158.9265
1,Cultural,Afghanistan,Asia and the Pacific,Minaret and Archaeological Remains of Jam,2002,1,64.515889,34.396417,70.0000
2,Cultural,Albania,Europe and North America,Historic Centres of Berat and Gjirokastra,2005,0,20.133333,40.069444,58.9000
3,Cultural,Albania,Europe and North America,Butrint,1992,0,20.026111,39.751111,0.0000
4,Cultural,Algeria,Arab States,Al Qal'a of Beni Hammad,1980,0,4.786840,35.818440,150.0000

In [23]:
c_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        1121 non-null   str
 1   states_name_en  1121 non-null   str
 2   region_en       1121 non-null   str
 3   name_en         1121 non-null   str
 4   date_inscribed  1121 non-null   int64
 5   danger          1121 non-null   int64
 6   longitude       1121 non-null   float64
 7   latitude        1121 non-null   float64
 8   area_hectares   1121 non-null   float64
dtypes: float64(3), int64(2), str(4)
memory usage: 78.9 KB

Rename Columns

In [24]:
c_df = c_df.rename(columns={
    'category': 'Category',
    'states_name_en': 'Country',
    'region_en': 'Region',
    'name_en': 'Site_Name',
    'date_inscribed': 'Year',
    'danger': 'Danger',
    'longitude': 'Longitude',
    'latitude': 'Latitude',
    'area_hectares': 'Area'
})

In [25]:
c_df.head()

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area
0,Cultural,Afghanistan,Asia and the Pacific,Cultural Landscape and Archaeological Remains ...,2003,1,67.825250,34.846940,158.9265
1,Cultural,Afghanistan,Asia and the Pacific,Minaret and Archaeological Remains of Jam,2002,1,64.515889,34.396417,70.0000
2,Cultural,Albania,Europe and North America,Historic Centres of Berat and Gjirokastra,2005,0,20.133333,40.069444,58.9000
3,Cultural,Albania,Europe and North America,Butrint,1992,0,20.026111,39.751111,0.0000
4,Cultural,Algeria,Arab States,Al Qal'a of Beni Hammad,1980,0,4.786840,35.818440,150.0000

In [26]:
c_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Category   1121 non-null   str
 1   Country    1121 non-null   str
 2   Region     1121 non-null   str
 3   Site_Name  1121 non-null   str
 4   Year       1121 non-null   int64
 5   Danger     1121 non-null   int64
 6   Longitude  1121 non-null   float64
 7   Latitude   1121 non-null   float64
 8   Area       1121 non-null   float64
dtypes: float64(3), int64(2), str(4)
memory usage: 78.9 KB

# Feature Engineering (Data transformation)

Create age of site column

In [27]:
c_df['Age']=2026-c_df['Year']  # It calculates how many years have passed since the site was added

In [28]:
c_df.head()

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age
0,Cultural,Afghanistan,Asia and the Pacific,Cultural Landscape and Archaeological Remains ...,2003,1,67.825250,34.846940,158.9265,23
1,Cultural,Afghanistan,Asia and the Pacific,Minaret and Archaeological Remains of Jam,2002,1,64.515889,34.396417,70.0000,24
2,Cultural,Albania,Europe and North America,Historic Centres of Berat and Gjirokastra,2005,0,20.133333,40.069444,58.9000,21
3,Cultural,Albania,Europe and North America,Butrint,1992,0,20.026111,39.751111,0.0000,34
4,Cultural,Algeria,Arab States,Al Qal'a of Beni Hammad,1980,0,4.786840,35.818440,150.0000,46

Create area category column

In [29]:

c_df['Area_Category'] = pd.cut(
    c_df['Area'],
    bins=[-1, 10000, 100000, c_df['Area'].max()],
    labels=['Small', 'Medium', 'Large']
)

Create danger status column

In [30]:

c_df['Danger_Status'] = c_df['Danger'].map({ 0: 'Safe',1: 'In Danger'}) # Numeric danger values are converted into readable labels.

Extract decade from year

In [31]:
c_df['Decade'] = (c_df['Year'] // 10) * 10   # In this step, the decade of inscription is created from the Year column.

In [32]:
c_df.head()

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age,Area_Category,Danger_Status,Decade
0,Cultural,Afghanistan,Asia and the Pacific,Cultural Landscape and Archaeological Remains ...,2003,1,67.825250,34.846940,158.9265,23,Small,In Danger,2000
1,Cultural,Afghanistan,Asia and the Pacific,Minaret and Archaeological Remains of Jam,2002,1,64.515889,34.396417,70.0000,24,Small,In Danger,2000
2,Cultural,Albania,Europe and North America,Historic Centres of Berat and Gjirokastra,2005,0,20.133333,40.069444,58.9000,21,Small,Safe,2000
3,Cultural,Albania,Europe and North America,Butrint,1992,0,20.026111,39.751111,0.0000,34,Small,Safe,1990
4,Cultural,Algeria,Arab States,Al Qal'a of Beni Hammad,1980,0,4.786840,35.818440,150.0000,46,Small,Safe,1980

In [33]:
c_df = c_df.sort_values(by='Year')  #the dataset is sorted based on Year.

In [34]:
c_df = c_df.reset_index(drop=True)

In [35]:
c_df.head()

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age,Area_Category,Danger_Status,Decade
0,Natural,United States of America,Europe and North America,Yellowstone National Park,1978,0,-110.827780,44.460560,898349.0,48,Large,Safe,1970
1,Cultural,United States of America,Europe and North America,Mesa Verde National Park,1978,0,-108.485556,37.261667,21043.0,48,Medium,Safe,1970
2,Cultural,Canada,Europe and North America,L’Anse aux Meadows National Historic Site,1978,0,-55.616667,51.466667,7991.0,48,Small,Safe,1970
3,Natural,Canada,Europe and North America,Nahanni National Park,1978,0,-125.589444,61.547222,476560.0,48,Large,Safe,1970
4,Cultural,Germany,Europe and North America,Aachen Cathedral,1978,0,6.084444,50.774444,0.2,48,Small,Safe,1970

In [37]:
c_df.to_csv('unesco_cleaned.csv', index=False)

print("File saved successfully")

File saved successfully